
import React from 'react'

export const metadata = {
     title: "App",
     description: "Generated by create next app",
};
export default function layout({children}) {
  return (
     <div className="child">
          {children}
     </div>
  )
}
